public class DATOS_GENERALESQuery
{
    public string DOCNUM { get; set; }
    public string idnumeracion { get; set; }
    public string numero { get; set; }
    public string idambiente { get; set; }
    public string fechadocumento { get; set; }
    public string fechavencimiento { get; set; }
    public string tipofactura { get; set; }
    public string tipooperacion { get; set; }
    public string notas { get; set; }
    public string moneda { get; set; }
    public string idreporte { get; set; }
    public string FP_idmetodopago { get; set; }
    public string FP_idmediopago { get; set; }
    public string FP_fechavencimiento { get; set; }
    public string FP_dias { get; set; }
    public string idconceptonota { get; set; }
    public string REF_idnumeracion { get; set; }
    public string REF_numero { get; set; }
    public string TDC_fecha { get; set; }
    public string TDC_moneda { get; set; }
    public string TDC_cambiominimo { get; set; }
    public string TDC_tasarepresentativa { get; set; }
    public string FACT_idtipopersona { get; set; }
    public string FACT_idactividadeconomica { get; set; }
    public string FACT_nombrecomercial { get; set; }
    public string FACT_idciudad { get; set; }
    public string FACT_direccion { get; set; }
    public string FACT_codigopostal { get; set; }
    public string FACT_nombres { get; set; }
    public string FACT_apellidos { get; set; }
    public string FACT_idtipodocumentoidentidad { get; set; }
    public string FACT_identificacion { get; set; }
    public string FACT_digitoverificacion { get; set; }
    public string FACT_idtiporegimen { get; set; }
    public string FACT_DIR_idciudad { get; set; }
    public string FACT_DIR_direccion { get; set; }
    public string FACT_DIR_codigopostal { get; set; }
    public string FACT_matriculamercantil { get; set; }
    public string FACT_emailcontacto { get; set; }
    public string FACT_emailentrega { get; set; }
    public string FACT_telefono { get; set; }
    public string FACT_obligaciones { get; set; }
    public string ADQUIR_idtipopersona { get; set; }
    public string ADQUIR_nombrecomercial { get; set; }
    public string ADQUIR_idciudad { get; set; }
    public string ADQUIR_direccion { get; set; }
    public string ADQUIR_nombres { get; set; }
    public string ADQUIR_apellidos { get; set; }
    public string ADQUIR_idtipodocumentoidentidad { get; set; }
    public string ADQUIR_identificacion { get; set; }
    public string ADQUIR_digitoverificacion { get; set; }
    public string ADQUIR_emailcontacto { get; set; }
    public string ADQUIR_emailentrega { get; set; }
    public string ADQUIR_telefono { get; set; }
    public string ADQUIR_obligaciones { get; set; }
    public string ORDENC_codigo { get; set; }
    public string TOTAL_totalbruto { get; set; }
    public string TOTAL_baseimponible { get; set; }
    public string TOTAL_totalbrutoconimpuestos { get; set; }
    public string TOTAL_totaldescuento { get; set; }
    public string TOTAL_totalcargos { get; set; }
    public string TOTAL_totalanticipos { get; set; }
    public string TOTAL_totalapagar { get; set; }
}
